if NEED_BLIP_BUFFER
libmednafen_marley_a_SOURCES	+=	sound/Blip_Buffer.cpp sound/Stereo_Buffer.cpp
endif

libmednafen_marley_a_SOURCES	+=	sound/Fir_Resampler.cpp

libmednafen_marley_a_SOURCES	+=	sound/WAVRecord.cpp
libmednafen_marley_a_SOURCES	+=	sound/okiadpcm.cpp

libmednafen_marley_a_SOURCES	+=	sound/DSPUtility.cpp
libmednafen_marley_a_SOURCES	+=	sound/SwiftResampler.cpp sound/OwlResampler.cpp

