.\" Manpage for marley.

.TH man 6 "19 Sep 2020" "0.1.5" "marley man page"
.SH NAME
marley \- Many Awesome Retro Linux Emulators, Yay! 
.SH SYNOPSIS 
marley [options]
.SH DESCRIPTION
Marley is a suite of console emulators plus a launcher app. 
In version 0.1.5, the bundle is comprised of Mednafen, Dolphin, 
Mupen64plus, PPSSPP, and PCSX2.
Marley's launcher interface is designed to be used with 
gamepads. Gamepads can be hotplugged and automatically detetcted
in the launcher interface. Marley also allows to configure 
the button assignment of a controller maunally. The controller settings 
are shared with all emulators. Marley allows to browse 
one's ROM collection and launch games for the GBA, GBC, NES, SNES, N64, 
PS1, PS2, PSP, Sega Genesis, Gamecube, and Wii.  Please make sure to 
install an OpenGl driver for your graphics card. If you have a 
Bluethooth gamepad, you need to pair it with your computer first 
before it can be used in Marley. The Wiimote is an exception and 
needs to be directly paired with Marley. On newer Wiimotes, you need 
to press 1 and 2 at the same time. For older Wiimote models, 
you need to press a small button in the battery compartment.

Happy retro gaming!

Use your controller or arrow keys/enter/escape on your keyboard to navigate.

Use "f" to toggle fullscreen.

Use "F5" to save and "F7" to load game states while playing.

Use the guide button to exit a game with no questions asked. The guide button is the big one in the middle.

Use "ESC" to exit.

Use B on the controller or arrow key down + LEFT_ALT on your keyboard to get from OFF to SHUTDOWN. You can shut down the computer from there.

Use "p" to print the current gamepad mapping(s).

Use "l" to print a list of detected controllers to the command line.

Visit https://github.com/beaumanvienna/marley for more information.
.SH OPTIONS
  --version             : print version
  --fullscreen, -f      : start in fullscreen mode
  --keepX11pointer, -k  : do not switch off X11 mouse pointer
.SH SEE ALSO

.SH BUGS

.SH AUTHOR
Team Marley. To contact us, open an issues ticket on https://github.com/beaumanvienna/marley. Pull requests are welcome!
