// Copyright (c) 2016- PPSSPP Project.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 2.0 or later versions.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License 2.0 for more details.

// A copy of the GPL 2.0 should have been included with the program.
// If not, see http://www.gnu.org/licenses/

// Official git repository and contact information can be found at
// https://github.com/hrydgard/ppsspp and http://www.ppsspp.org/.

#pragma once

#ifdef __ANDROID__
#define VK_USE_PLATFORM_ANDROID_KHR
#elif defined(_WIN32)
#define VK_USE_PLATFORM_WIN32_KHR
#define WIN32_LEAN_AND_MEAN
#ifndef NOMINMAX
#define NOMINMAX
#endif
#elif defined(__APPLE__)
#define VK_USE_PLATFORM_METAL_EXT
#endif

#define VK_NO_PROTOTYPES

#include "ext/vulkan/vulkan.h"

extern PFN_PvkCreateInstance PvkCreateInstance;
extern PFN_PvkDestroyInstance PvkDestroyInstance;
extern PFN_PvkEnumeratePhysicalDevices PvkEnumeratePhysicalDevices;
extern PFN_PvkGetPhysicalDeviceFeatures PvkGetPhysicalDeviceFeatures;
extern PFN_PvkGetPhysicalDeviceFormatProperties PvkGetPhysicalDeviceFormatProperties;
extern PFN_PvkGetPhysicalDeviceImageFormatProperties PvkGetPhysicalDeviceImageFormatProperties;
extern PFN_PvkGetPhysicalDeviceProperties PvkGetPhysicalDeviceProperties;
extern PFN_PvkGetPhysicalDeviceQueueFamilyProperties PvkGetPhysicalDeviceQueueFamilyProperties;
extern PFN_PvkGetPhysicalDeviceMemoryProperties PvkGetPhysicalDeviceMemoryProperties;
extern PFN_PvkGetInstanceProcAddr PvkGetInstanceProcAddr;
extern PFN_PvkGetDeviceProcAddr PvkGetDeviceProcAddr;
extern PFN_PvkCreateDevice PvkCreateDevice;
extern PFN_PvkDestroyDevice PvkDestroyDevice;
extern PFN_PvkEnumerateInstanceExtensionProperties PvkEnumerateInstanceExtensionProperties;
extern PFN_PvkEnumerateDeviceExtensionProperties PvkEnumerateDeviceExtensionProperties;
extern PFN_PvkEnumerateInstanceLayerProperties PvkEnumerateInstanceLayerProperties;
extern PFN_PvkEnumerateDeviceLayerProperties PvkEnumerateDeviceLayerProperties;
extern PFN_PvkGetDeviceQueue PvkGetDeviceQueue;
extern PFN_PvkQueueSubmit PvkQueueSubmit;
extern PFN_PvkQueueWaitIdle PvkQueueWaitIdle;
extern PFN_PvkDeviceWaitIdle PvkDeviceWaitIdle;
extern PFN_PvkAllocateMemory PvkAllocateMemory;
extern PFN_PvkFreeMemory PvkFreeMemory;
extern PFN_PvkMapMemory PvkMapMemory;
extern PFN_PvkUnmapMemory PvkUnmapMemory;
extern PFN_PvkFlushMappedMemoryRanges PvkFlushMappedMemoryRanges;
extern PFN_PvkInvalidateMappedMemoryRanges PvkInvalidateMappedMemoryRanges;
extern PFN_PvkGetDeviceMemoryCommitment PvkGetDeviceMemoryCommitment;
extern PFN_PvkBindBufferMemory PvkBindBufferMemory;
extern PFN_PvkBindImageMemory PvkBindImageMemory;
extern PFN_PvkGetBufferMemoryRequirements PvkGetBufferMemoryRequirements;
extern PFN_PvkGetImageMemoryRequirements PvkGetImageMemoryRequirements;
extern PFN_PvkGetImageSparseMemoryRequirements PvkGetImageSparseMemoryRequirements;
extern PFN_PvkGetPhysicalDeviceSparseImageFormatProperties PvkGetPhysicalDeviceSparseImageFormatProperties;
extern PFN_PvkQueueBindSparse PvkQueueBindSparse;
extern PFN_PvkCreateFence PvkCreateFence;
extern PFN_PvkDestroyFence PvkDestroyFence;
extern PFN_PvkResetFences PvkResetFences;
extern PFN_PvkGetFenceStatus PvkGetFenceStatus;
extern PFN_PvkWaitForFences PvkWaitForFences;
extern PFN_PvkCreateSemaphore PvkCreateSemaphore;
extern PFN_PvkDestroySemaphore PvkDestroySemaphore;
extern PFN_PvkCreateEvent PvkCreateEvent;
extern PFN_PvkDestroyEvent PvkDestroyEvent;
extern PFN_PvkGetEventStatus PvkGetEventStatus;
extern PFN_PvkSetEvent PvkSetEvent;
extern PFN_PvkResetEvent PvkResetEvent;
extern PFN_PvkCreateQueryPool PvkCreateQueryPool;
extern PFN_PvkDestroyQueryPool PvkDestroyQueryPool;
extern PFN_PvkGetQueryPoolResults PvkGetQueryPoolResults;
extern PFN_PvkCreateBuffer PvkCreateBuffer;
extern PFN_PvkDestroyBuffer PvkDestroyBuffer;
extern PFN_PvkCreateBufferView PvkCreateBufferView;
extern PFN_PvkDestroyBufferView PvkDestroyBufferView;
extern PFN_PvkCreateImage PvkCreateImage;
extern PFN_PvkDestroyImage PvkDestroyImage;
extern PFN_PvkGetImageSubresourceLayout PvkGetImageSubresourceLayout;
extern PFN_PvkCreateImageView PvkCreateImageView;
extern PFN_PvkDestroyImageView PvkDestroyImageView;
extern PFN_PvkCreateShaderModule PvkCreateShaderModule;
extern PFN_PvkDestroyShaderModule PvkDestroyShaderModule;
extern PFN_PvkCreatePipelineCache PvkCreatePipelineCache;
extern PFN_PvkDestroyPipelineCache PvkDestroyPipelineCache;
extern PFN_PvkGetPipelineCacheData PvkGetPipelineCacheData;
extern PFN_PvkMergePipelineCaches PvkMergePipelineCaches;
extern PFN_PvkCreateGraphicsPipelines PvkCreateGraphicsPipelines;
extern PFN_PvkCreateComputePipelines PvkCreateComputePipelines;
extern PFN_PvkDestroyPipeline PvkDestroyPipeline;
extern PFN_PvkCreatePipelineLayout PvkCreatePipelineLayout;
extern PFN_PvkDestroyPipelineLayout PvkDestroyPipelineLayout;
extern PFN_PvkCreateSampler PvkCreateSampler;
extern PFN_PvkDestroySampler PvkDestroySampler;
extern PFN_PvkCreateDescriptorSetLayout PvkCreateDescriptorSetLayout;
extern PFN_PvkDestroyDescriptorSetLayout PvkDestroyDescriptorSetLayout;
extern PFN_PvkCreateDescriptorPool PvkCreateDescriptorPool;
extern PFN_PvkDestroyDescriptorPool PvkDestroyDescriptorPool;
extern PFN_PvkResetDescriptorPool PvkResetDescriptorPool;
extern PFN_PvkAllocateDescriptorSets PvkAllocateDescriptorSets;
extern PFN_PvkFreeDescriptorSets PvkFreeDescriptorSets;
extern PFN_PvkUpdateDescriptorSets PvkUpdateDescriptorSets;
extern PFN_PvkCreateFramebuffer PvkCreateFramebuffer;
extern PFN_PvkDestroyFramebuffer PvkDestroyFramebuffer;
extern PFN_PvkCreateRenderPass PvkCreateRenderPass;
extern PFN_PvkDestroyRenderPass PvkDestroyRenderPass;
extern PFN_PvkGetRenderAreaGranularity PvkGetRenderAreaGranularity;
extern PFN_PvkCreateCommandPool PvkCreateCommandPool;
extern PFN_PvkDestroyCommandPool PvkDestroyCommandPool;
extern PFN_PvkResetCommandPool PvkResetCommandPool;
extern PFN_PvkAllocateCommandBuffers PvkAllocateCommandBuffers;
extern PFN_PvkFreeCommandBuffers PvkFreeCommandBuffers;
extern PFN_PvkBeginCommandBuffer PvkBeginCommandBuffer;
extern PFN_PvkEndCommandBuffer PvkEndCommandBuffer;
extern PFN_PvkResetCommandBuffer PvkResetCommandBuffer;
extern PFN_PvkCmdBindPipeline PvkCmdBindPipeline;
extern PFN_PvkCmdSetViewport PvkCmdSetViewport;
extern PFN_PvkCmdSetScissor PvkCmdSetScissor;
extern PFN_PvkCmdSetLineWidth PvkCmdSetLineWidth;
extern PFN_PvkCmdSetDepthBias PvkCmdSetDepthBias;
extern PFN_PvkCmdSetBlendConstants PvkCmdSetBlendConstants;
extern PFN_PvkCmdSetDepthBounds PvkCmdSetDepthBounds;
extern PFN_PvkCmdSetStencilCompareMask PvkCmdSetStencilCompareMask;
extern PFN_PvkCmdSetStencilWriteMask PvkCmdSetStencilWriteMask;
extern PFN_PvkCmdSetStencilReference PvkCmdSetStencilReference;
extern PFN_PvkCmdBindDescriptorSets PvkCmdBindDescriptorSets;
extern PFN_PvkCmdBindIndexBuffer PvkCmdBindIndexBuffer;
extern PFN_PvkCmdBindVertexBuffers PvkCmdBindVertexBuffers;
extern PFN_PvkCmdDraw PvkCmdDraw;
extern PFN_PvkCmdDrawIndexed PvkCmdDrawIndexed;
extern PFN_PvkCmdDrawIndirect PvkCmdDrawIndirect;
extern PFN_PvkCmdDrawIndexedIndirect PvkCmdDrawIndexedIndirect;
extern PFN_PvkCmdDispatch PvkCmdDispatch;
extern PFN_PvkCmdDispatchIndirect PvkCmdDispatchIndirect;
extern PFN_PvkCmdCopyBuffer PvkCmdCopyBuffer;
extern PFN_PvkCmdCopyImage PvkCmdCopyImage;
extern PFN_PvkCmdBlitImage PvkCmdBlitImage;
extern PFN_PvkCmdCopyBufferToImage PvkCmdCopyBufferToImage;
extern PFN_PvkCmdCopyImageToBuffer PvkCmdCopyImageToBuffer;
extern PFN_PvkCmdUpdateBuffer PvkCmdUpdateBuffer;
extern PFN_PvkCmdFillBuffer PvkCmdFillBuffer;
extern PFN_PvkCmdClearColorImage PvkCmdClearColorImage;
extern PFN_PvkCmdClearDepthStencilImage PvkCmdClearDepthStencilImage;
extern PFN_PvkCmdClearAttachments PvkCmdClearAttachments;
extern PFN_PvkCmdResolveImage PvkCmdResolveImage;
extern PFN_PvkCmdSetEvent PvkCmdSetEvent;
extern PFN_PvkCmdResetEvent PvkCmdResetEvent;
extern PFN_PvkCmdWaitEvents PvkCmdWaitEvents;
extern PFN_PvkCmdPipelineBarrier PvkCmdPipelineBarrier;
extern PFN_PvkCmdBeginQuery PvkCmdBeginQuery;
extern PFN_PvkCmdEndQuery PvkCmdEndQuery;
extern PFN_PvkCmdResetQueryPool PvkCmdResetQueryPool;
extern PFN_PvkCmdWriteTimestamp PvkCmdWriteTimestamp;
extern PFN_PvkCmdCopyQueryPoolResults PvkCmdCopyQueryPoolResults;
extern PFN_PvkCmdPushConstants PvkCmdPushConstants;
extern PFN_PvkCmdBeginRenderPass PvkCmdBeginRenderPass;
extern PFN_PvkCmdNextSubpass PvkCmdNextSubpass;
extern PFN_PvkCmdEndRenderPass PvkCmdEndRenderPass;
extern PFN_PvkCmdExecuteCommands PvkCmdExecuteCommands;

#ifdef __ANDROID__
extern PFN_vkCreateAndroidSurfaceKHR vkCreateAndroidSurfaceKHR;
#elif defined(_WIN32)
extern PFN_vkCreateWin32SurfaceKHR vkCreateWin32SurfaceKHR;
#elif defined(VK_USE_PLATFORM_METAL_EXT)
extern PFN_vkCreateMetalSurfaceEXT vkCreateMetalSurfaceEXT;
#endif
#if defined(VK_USE_PLATFORM_XLIB_KHR)
extern PFN_PvkCreateXlibSurfaceKHR PvkCreateXlibSurfaceKHR;
#endif
#if defined(VK_USE_PLATFORM_WAYLAND_KHR)
extern PFN_vkCreateWaylandSurfaceKHR vkCreateWaylandSurfaceKHR;
#endif

extern PFN_PvkDestroySurfaceKHR PvkDestroySurfaceKHR;

// Simple loader for the WSI extension.
extern PFN_PvkGetPhysicalDeviceSurfaceSupportKHR PvkGetPhysicalDeviceSurfaceSupportKHR;
extern PFN_PvkGetPhysicalDeviceSurfaceCapabilitiesKHR PvkGetPhysicalDeviceSurfaceCapabilitiesKHR;
extern PFN_PvkGetPhysicalDeviceSurfaceFormatsKHR PvkGetPhysicalDeviceSurfaceFormatsKHR;
extern PFN_PvkGetPhysicalDeviceSurfacePresentModesKHR PvkGetPhysicalDeviceSurfacePresentModesKHR;

extern PFN_PvkCreateSwapchainKHR PvkCreateSwapchainKHR;
extern PFN_PvkDestroySwapchainKHR PvkDestroySwapchainKHR;
extern PFN_PvkGetSwapchainImagesKHR PvkGetSwapchainImagesKHR;
extern PFN_PvkAcquireNextImageKHR PvkAcquireNextImageKHR;
extern PFN_PvkQueuePresentKHR PvkQueuePresentKHR;

extern PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT;
extern PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT;
extern PFN_vkCmdBeginDebugUtilsLabelEXT vkCmdBeginDebugUtilsLabelEXT;
extern PFN_vkCmdEndDebugUtilsLabelEXT vkCmdEndDebugUtilsLabelEXT;
extern PFN_vkCmdInsertDebugUtilsLabelEXT vkCmdInsertDebugUtilsLabelEXT;
extern PFN_PvkSetDebugUtilsObjectNameEXT PvkSetDebugUtilsObjectNameEXT;
extern PFN_vkSetDebugUtilsObjectTagEXT vkSetDebugUtilsObjectTagEXT;

// Assorted other extensions.
extern PFN_PvkGetBufferMemoryRequirements2KHR PvkGetBufferMemoryRequirements2KHR;
extern PFN_PvkGetImageMemoryRequirements2KHR PvkGetImageMemoryRequirements2KHR;
extern PFN_vkGetMemoryHostPointerPropertiesEXT vkGetMemoryHostPointerPropertiesEXT;
extern PFN_PvkGetPhysicalDeviceProperties2KHR PvkGetPhysicalDeviceProperties2KHR;
extern PFN_PvkGetPhysicalDeviceFeatures2KHR PvkGetPhysicalDeviceFeatures2KHR;

// For fast extension-enabled checks.
struct VulkanExtensions {
	bool EXT_debug_utils;
	bool KHR_maintenance1; // required for KHR_create_renderpass2
	bool KHR_maintenance2;
	bool KHR_maintenance3;
	bool KHR_multiview;  // required for KHR_create_renderpass2
	bool KHR_get_memory_requirements2;
	bool KHR_dedicated_allocation;
	bool KHR_create_renderpass2;
	bool EXT_external_memory_host;
	bool KHR_get_physical_device_properties2;
	bool KHR_depth_stencil_resolve;
	bool EXT_shader_stencil_export;
	// bool EXT_depth_range_unrestricted;  // Allows depth outside [0.0, 1.0] in 32-bit float depth buffers.
};

// Way to do a quick check before even attempting to load.
bool VulkanMayBeAvailable();
void VulkanSetAvailable(bool available);

bool VulkanLoad();
void VulkanLoadInstanceFunctions(VkInstance instance, const VulkanExtensions &enabledExtensions);
void VulkanLoadDeviceFunctions(VkDevice device, const VulkanExtensions &enabledExtensions);
void VulkanFree();
