#standalone dolphin test version
COMPILER_ARTIFACTS = --std=c++17 -I/usr/include/SDL2 -I../../dolphin/Source/Core

LINKER_OBJECTS 	 = ../../dolphin/build/Source/Core/DolphinNoGUI/libdolphin-emu-nogui.a
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/Core/libcore.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/UICommon/libuicommon.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/imgui/libimgui.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/Null/libvideonull.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/OGL/libvideoogl.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/Software/libvideosoftware.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/Vulkan/libvideovulkan.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoCommon/libvideocommon.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/Core/libcore.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/Null/libvideonull.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/OGL/libvideoogl.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/Software/libvideosoftware.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoBackends/Vulkan/libvideovulkan.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/VideoCommon/libvideocommon.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/AudioCommon/libaudiocommon.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/soundtouch/libSoundTouch.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/FreeSurround/libFreeSurround.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/cubeb/libcubeb.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/DiscIO/libdiscio.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/InputCommon/libinputcommon.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/hidapi/libhidapi.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/glslang/libglslang.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/imgui/libimgui.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/xxhash/libxxhash.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/Common/libcommon.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/enet/libenet.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/pugixml/libpugixml.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/fmt/libfmt.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/Bochs_disasm/libbdisasm.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/cpp-optparse/libcpp-optparse.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/minizip/libminizip.a 
LINKER_OBJECTS 	+= ../../dolphin/build/Source/Core/../../Externals/discord-rpc/src/libdiscord-rpc.a  
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libQt5Widgets.so
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libasound.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libpulse.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/liblzo2.so
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libbluetooth.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libavformat.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libavcodec.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libswscale.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libavutil.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libQt5Gui.so
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libQt5Core.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libmbedtls.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libmbedx509.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libmbedcrypto.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libcurl.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libICE.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libX11.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libXext.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libSM.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libGLX.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libminiupnpc.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libusb-1.0.so 
LINKER_OBJECTS 	+= /usr/lib/x86_64-linux-gnu/libevdev.so 
LINKER_OBJECTS 	+= /lib/x86_64-linux-gnu/libudev.so 
LINKER_OBJECTS 	+= -lXi 
LINKER_OBJECTS 	+= -lsfml-network 
LINKER_OBJECTS 	+= -lsfml-system 
LINKER_OBJECTS 	+= -ludev 
LINKER_OBJECTS 	+= -lc 
LINKER_OBJECTS 	+= -lpng 
LINKER_OBJECTS  += -ldl
LINKER_OBJECTS 	+= -lrt 
LINKER_OBJECTS 	+= -lXrandr 
LINKER_OBJECTS 	+= -lpulse 
LINKER_OBJECTS 	+= -lsndio
LINKER_OBJECTS 	+= -lpthread
LINKER_OBJECTS 	+= -lSDL2
LINKER_OBJECTS 	+= -lz
LINKER_OBJECTS 	+= -lEGL
LINKER_OBJECTS 	+= -lGL
LINKER_OBJECTS 	+= -lGLU



all: DOLPHIN

DOLPHIN:
	$(info   *************** tests make dolphin ***************)
	$(MAKE) -C ../../dolphin/build all -j8
	g++ $(COMPILER_ARTIFACTS) -o DOLPHIN main.cpp $(LINKER_OBJECTS)
#-g3 -O0 -ggdb

clean:
	$(info   *************** tests dolphin clean ***************)
	rm -f *.o DOLPHIN

