#pragma once

enum ButtonStatesTwoStates {
    NO_ICON_BUTTON_STATE_NOT_FOCUSED = 0,
    NO_ICON_BUTTON_STATE_FOCUSED,
};

enum ButtonStatesFourStates {
    BUTTON_STATE_NOT_FOCUSED = 0,
    BUTTON_STATE_NOT_FOCUSED_DEPRESSED,
    BUTTON_STATE_FOCUSED,
    BUTTON_STATE_FOCUSED_DEPRESSED,
};
